/**
 * Base de Datos Oficial de las 80 Cartas del Set Base - Cometa Champions TCG
 */

const CLANS_INFO = {
  milenarios: {
    id: "milenarios",
    name: "Milenarios",
    symbol: "🌳",
    color: "#30d158",
    accentColor: "#248a3d",
    bgGradient: "from-emerald-950 via-teal-900 to-black",
    icon: "Clans_Icon/Milennials_B.png",
    flag: "cometaKombat/flag_milenials.png",
    beats: "fugitivos",
    beatenBy: "miticos",
    description: "Guardianes ancestrales de la naturaleza y de la tradición milenaria de los trompos. Su estilo combina resistencia sólida y sabiduría defensiva.",
    bonus: "+1 Daño contra Fugitivos (⛓️)"
  },
  fugitivos: {
    id: "fugitivos",
    name: "Fugitivos",
    symbol: "⛓️",
    color: "#ff9f0a",
    accentColor: "#c97800",
    bgGradient: "from-amber-950 via-orange-950 to-black",
    icon: "Clans_Icon/Fugitives_B.png",
    flag: "cometaKombat/flag_fugitives.png",
    beats: "depredadores",
    beatenBy: "milenarios",
    description: "Rebeldes indomables de las calles y los suburbios industriales. Destacan por su astucia impredecible, trampas y contragolpes letales.",
    bonus: "+1 Daño contra Depredadores (🪓)"
  },
  depredadores: {
    id: "depredadores",
    name: "Depredadores",
    symbol: "🪓",
    color: "#ff453a",
    accentColor: "#d70015",
    bgGradient: "from-red-950 via-orange-950 to-black",
    icon: "Clans_Icon/Predators_B.png",
    flag: "cometaKombat/flag_predators.png",
    beats: "miticos",
    beatenBy: "fugitivos",
    description: "Cazadores feroces de instinto puro. Su filosofía es el ataque implacable y el poder demoledor que arrasa cualquier defensa.",
    bonus: "+1 Daño contra Míticos (🐉)"
  },
  miticos: {
    id: "miticos",
    name: "Míticos",
    symbol: "🐉",
    color: "#bf5af2",
    accentColor: "#8619b8",
    bgGradient: "from-purple-950 via-indigo-950 to-black",
    icon: "Clans_Icon/Mythicals_B.png",
    flag: "cometaKombat/flag_mithicals.png",
    beats: "milenarios",
    beatenBy: "depredadores",
    description: "Maestros del Cristal Cometa y portadores de magia ancestral. Manipulan la energía cósmica y los cielos con poderes trascendentes.",
    bonus: "+1 Daño contra Milenarios (🌳)"
  },
  neutral: {
    id: "neutral",
    name: "Neutral",
    symbol: "⭐",
    color: "#f5c518",
    accentColor: "#b37b00",
    bgGradient: "from-amber-950 via-yellow-950 to-black",
    icon: "assets/mockups/azteca_card_milenarios_mockup_1773452793855.png",
    flag: "cometaKombat/box.png",
    beats: null,
    beatenBy: null,
    description: "Zonas legendarias y cartas ecuménicas donde convergen los cuatro clanes bajo reglas neutrales.",
    bonus: "Equilibrio absoluto entre todos los clanes"
  }
};

const CARDS_DATABASE = [
  // ==========================================
  // CATEGORÍA 1: HÉROES CHAMPIONS (20 CARTAS)
  // ==========================================
  {
    id: "CC-01",
    name: "Avispón",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "depredadores",
    cost: 2,
    attack: 3,
    defense: 1,
    image: "CC_Export/Avispon.png",
    rarity: "Común",
    quote: "¡Soy más rápido que el viento!",
    description: "Maestro de la velocidad aérea. Sus ataques en picada desestabilizan a cualquier rival antes de que toque el suelo."
  },
  {
    id: "CC-02",
    name: "Azteca",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "milenarios",
    cost: 6,
    attack: 6,
    defense: 6,
    image: "CC_Export/Azteca.png",
    rarity: "Épica",
    quote: "¡La historia está de mi lado!",
    description: "Fuerte, sabio y honorable. Canaliza el poder de templos ancestrales para resistir y devolver golpes titánicos."
  },
  {
    id: "CC-03",
    name: "Cometín",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "milenarios",
    cost: 2,
    attack: 2,
    defense: 2,
    image: "CC_Export/Cometin.png",
    rarity: "Común",
    quote: "¡Nunca me detengo!",
    description: "Energía inagotable. Siempre listo para la próxima jugada con un optimismo que inspira a todo su equipo."
  },
  {
    id: "CC-04",
    name: "Diamante",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "fugitivos",
    cost: 4,
    attack: 1,
    defense: 7,
    image: "CC_Export/Diamante.png",
    rarity: "Rara",
    quote: "¡Fuerte como un diamante!",
    description: "Un muro impenetrable. Sus defensas cristalinas absorben los impactos más destructivos del rival."
  },
  {
    id: "CC-05",
    name: "Diamantín",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "milenarios",
    cost: 1,
    attack: 1,
    defense: 2,
    image: "CC_Export/Diamantin.png",
    rarity: "Común",
    quote: "¡Brillante y fuerte!",
    description: "Pequeño pero con corazón indomable. Su tamaño le permite escabullirse y asistir en momentos críticos."
  },
  {
    id: "CC-06",
    name: "Draky",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "fugitivos",
    cost: 3,
    attack: 2,
    defense: 4,
    image: "CC_Export/Draky.png",
    rarity: "Común",
    quote: "¡La aventura apenas comienza!",
    description: "Curioso e ingenioso. Encuentra siempre atajos y trampas para desarmar la estrategia del oponente."
  },
  {
    id: "CC-07",
    name: "Espectro",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "miticos",
    cost: 4,
    attack: 4,
    defense: 3,
    image: "CC_Export/Espectro.png",
    rarity: "Rara",
    quote: "¡El misterio es mi fuerza!",
    description: "Ataca desde las sombras cósmicas. Difícil de rastrear y letal al manifestar su energía fantasmal."
  },
  {
    id: "CC-08",
    name: "Fénix",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "miticos",
    cost: 6,
    attack: 4,
    defense: 6,
    image: "CC_Export/Fenix_.png",
    rarity: "Épica",
    quote: "¡El fuego me guía!",
    description: "Cuando cae en combate, su espíritu ígneo promete resurgir de las cenizas con mayor determinación."
  },
  {
    id: "CC-09",
    name: "Jumbo Cobra",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "fugitivos",
    cost: 5,
    attack: 5,
    defense: 4,
    image: "CC_Export/Jumbo Cobra.png",
    rarity: "Rara",
    quote: "¡Siempre me levanto más fuerte!",
    description: "Un titán urbano con fuerza de compresión devastadora. Ningún obstáculo resiste su embestida."
  },
  {
    id: "CC-10",
    name: "King Cobra",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "depredadores",
    cost: 7,
    attack: 6,
    defense: 7,
    image: "CC_Export/King Cobra.png",
    rarity: "Legendaria",
    quote: "¡El rey nunca pierde!",
    description: "Líder soberano de los Depredadores. Combina intimidación psicológica, fuerza imperial y reflejos venenosos."
  },
  {
    id: "CC-11",
    name: "Orión",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "miticos",
    cost: 4,
    attack: 2,
    defense: 5,
    image: "CC_Export/Orion.png",
    rarity: "Rara",
    quote: "¡Todo está en la estrategia!",
    description: "Estratega cósmica. Lee los movimientos del oponente como constelaciones antes de dictar su siguiente jugada."
  },
  {
    id: "CC-12",
    name: "Panther",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "depredadores",
    cost: 4,
    attack: 5,
    defense: 2,
    image: "CC_Export/Panther.png",
    rarity: "Rara",
    quote: "¡Silenciosa como una pantera!",
    description: "Cazadora sigilosa de la jungla oscura. Su ataque sorpresa anula a defensores desprevenidos."
  },
  {
    id: "CC-13",
    name: "Rex",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "miticos",
    cost: 8,
    attack: 8,
    defense: 8,
    image: "CC_Export/Rex.png",
    rarity: "Legendaria",
    quote: "¡El poder está en mis manos!",
    description: "La cumbre del poder místico. Cada pisada en la arena hace temblar la mesa de juego."
  },
  {
    id: "CC-14",
    name: "Silver",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "milenarios",
    cost: 3,
    attack: 3,
    defense: 3,
    image: "CC_Export/Silver.png",
    rarity: "Común",
    quote: "¡El estilo lo es todo!",
    description: "Refinado y certero. Su armadura plateada desvía la hostilidad rival con elegancia acrobática."
  },
  {
    id: "CC-15",
    name: "Spider",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "fugitivos",
    cost: 3,
    attack: 1,
    defense: 4,
    image: "CC_Export/Spider.png",
    rarity: "Común",
    quote: "¡La paciencia es clave!",
    description: "Teje redes tácticas en la arena. Inmoviliza las cartas más veloces del oponente con frialdad calculada."
  },
  {
    id: "CC-16",
    name: "Tigre",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "depredadores",
    cost: 5,
    attack: 6,
    defense: 4,
    image: "CC_Export/Tigre.png",
    rarity: "Rara",
    quote: "¡Soy una fuerza imparable!",
    description: "Ferocidad felina desatada. Su rugido intimida y sus zarpazos abren brechas en la defensa enemiga."
  },
  {
    id: "CC-17",
    name: "Turbo Cobra",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "milenarios",
    cost: 1,
    attack: 2,
    defense: 1,
    image: "CC_Export/Turbo Cobra.png",
    rarity: "Común",
    quote: "¡A toda velocidad!",
    description: "Pequeña víbora hiperveloz. Perfecta para un arranque agresivo en los primeros turnos."
  },
  {
    id: "CC-18",
    name: "Turbo Dragón",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "depredadores",
    cost: 7,
    attack: 7,
    defense: 5,
    image: "CC_Export/Turbo Dragon.png",
    rarity: "Épica",
    quote: "¡El dragón nunca se rinde!",
    description: "El señor del fuego y la furia de los Depredadores. Alza el vuelo para incinerar las filas rivales."
  },
  {
    id: "CC-19",
    name: "Turbo Flash",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "miticos",
    cost: 3,
    attack: 4,
    defense: 2,
    image: "CC_Export/Turbo Flash.png",
    rarity: "Común",
    quote: "¡Soy más rápido que un rayo!",
    description: "El relámpago místico. Golpea y cambia de posición en un parpadeo de luz estelar."
  },
  {
    id: "CC-20",
    name: "Turbo King",
    category: "champions",
    categoryName: "Héroes Champions",
    clan: "fugitivos",
    cost: 6,
    attack: 5,
    defense: 5,
    image: "CC_Export/Turbo King.png",
    rarity: "Épica",
    quote: "¡El rey del turbo está aquí!",
    description: "Unión perfecta de velocidad sobre ruedas y fuerza de choque. Domina la vanguardia de los Fugitivos."
  },

  // ==========================================
  // CATEGORÍA 2: BESTIAS KOMBAT (20 CARTAS)
  // ==========================================
  {
    id: "CK-01",
    name: "Avispón (Enjambre)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "depredadores",
    cost: 3,
    attack: 4,
    defense: 2,
    image: "CK_Export/Avispon.png",
    rarity: "Rara",
    quote: "¡El zumbido ancestral que anuncia la caída!",
    description: "La criatura primitiva que domina los cielos de la arena a velocidades hipersónicas."
  },
  {
    id: "CK-02",
    name: "Azteca (Guardián)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "milenarios",
    cost: 7,
    attack: 7,
    defense: 7,
    image: "CK_Export/Azteca.png",
    rarity: "Legendaria",
    quote: "¡La roca viva jamás se doblega!",
    description: "El coloso de piedra milenario despertado para resguardar los templos sagrados de Kamino."
  },
  {
    id: "CK-03",
    name: "Cometín (Rayo Astral)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "milenarios",
    cost: 3,
    attack: 3,
    defense: 3,
    image: "CK_Export/Cometin.png",
    rarity: "Rara",
    quote: "¡Luz que viaja a través de los siglos!",
    description: "Encarnación pura de una estrella primigenia que surca los valles milenarios."
  },
  {
    id: "CK-04",
    name: "Diamante (Leviatán)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "fugitivos",
    cost: 5,
    attack: 2,
    defense: 8,
    image: "CK_Export/Diamante.png",
    rarity: "Épica",
    quote: "¡Rompe tus armas contra mi cuerpo!",
    description: "Monstruo telúrico forjado con núcleos de diamantes inquebrantables. Su peso deforma el terreno."
  },
  {
    id: "CK-05",
    name: "Diamantín (Cristalino)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "milenarios",
    cost: 2,
    attack: 2,
    defense: 3,
    image: "CK_Export/Diamantin.png",
    rarity: "Común",
    quote: "¡Destellos que ciegan al cazador!",
    description: "Pequeño gólem brillante que proyecta campos de fuerza protectores sobre sus aliados."
  },
  {
    id: "CK-06",
    name: "Draky (Aparecido)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "fugitivos",
    cost: 4,
    attack: 3,
    defense: 5,
    image: "CK_Export/Draky.png",
    rarity: "Rara",
    quote: "¡De la bruma salgo, en la bruma venzo!",
    description: "Un dragón etéreo nacido de la energía residual del Cristal Cometa. Desconcierta con trucos dimensionales."
  },
  {
    id: "CK-07",
    name: "Espectro (Sombra)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "miticos",
    cost: 5,
    attack: 5,
    defense: 3,
    image: "CK_Export/Espectro.png",
    rarity: "Épica",
    quote: "¡El vacío te reclama!",
    description: "Espíritu supremo que habita en la dimensión umbría. Drena la vitalidad de sus presas."
  },
  {
    id: "CK-08",
    name: "Fénix (Ave Ígnea)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "miticos",
    cost: 7,
    attack: 5,
    defense: 7,
    image: "CK_Export/Fenix_.png",
    rarity: "Legendaria",
    quote: "¡Cenizas al viento, fuego eterno!",
    description: "El ave divina inmortal de Kamino. Sus llamaradas renuevan a los aliados y calcinan a los tiranos."
  },
  {
    id: "CK-09",
    name: "Jumbo Cobra (Sierpe)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "fugitivos",
    cost: 6,
    attack: 6,
    defense: 5,
    image: "CK_Export/Jumbo Cobra.png",
    rarity: "Épica",
    quote: "¡Siente la asfixia del abismo!",
    description: "Serpiente colosal subterránea capaz de derribar fortalezas con un coletazo de pura masa muscular."
  },
  {
    id: "CK-10",
    name: "King Cobra (Rey Bestia)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "depredadores",
    cost: 8,
    attack: 7,
    defense: 8,
    image: "CK_Export/King Cobra.png",
    rarity: "Legendaria",
    quote: "¡Todas las bestias bajan la cabeza ante mí!",
    description: "La bestia alfa originaria de los Depredadores. Su veneno es legendario y su dominio, absoluto."
  },
  {
    id: "CK-11",
    name: "Orión (Entidad Cósmica)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "miticos",
    cost: 5,
    attack: 3,
    defense: 6,
    image: "CK_Export/Orion.png",
    rarity: "Épica",
    quote: "¡El mapa estelar predijo tu derrota!",
    description: "Entidad celeste que canaliza las órbitas cósmicas para redirigir los ataques del oponente."
  },
  {
    id: "CK-12",
    name: "Panther (Cazadora)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "depredadores",
    cost: 5,
    attack: 6,
    defense: 3,
    image: "CK_Export/Panther.png",
    rarity: "Épica",
    quote: "¡No escucharás el golpe hasta que estés en el suelo!",
    description: "La fiera nocturna más temida de las selvas prohibidas. Su ataque inicial duplica el impacto crítico."
  },
  {
    id: "CK-13",
    name: "Rex (Tirano Ancestral)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "miticos",
    cost: 9,
    attack: 9,
    defense: 9,
    image: "CK_Export/Rex.png",
    rarity: "Legendaria",
    quote: "¡RUGE EL CREADOR DE SISMOS!",
    description: "El dinosaurio rey indiscutible de las tierras primigenias. Una catástrofe viviente en el campo de batalla."
  },
  {
    id: "CK-14",
    name: "Silver (Metálico)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "milenarios",
    cost: 4,
    attack: 4,
    defense: 4,
    image: "CK_Export/Silver.png",
    rarity: "Rara",
    quote: "¡Plata pura que refleja el destino!",
    description: "Criatura de mercurio y plata endurecida. Sus extremidades se afilan como navajas vivientes."
  },
  {
    id: "CK-15",
    name: "Spider (Viuda Escurridiza)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "fugitivos",
    cost: 4,
    attack: 2,
    defense: 5,
    image: "CK_Export/Spider.png",
    rarity: "Rara",
    quote: "¡Cada hilo es una trampa sin salida!",
    description: "Arácnido gigante que teje telarañas cargadas con estática del Cristal Cometa para inmovilizar ejércitos."
  },
  {
    id: "CK-16",
    name: "Tigre (Dientes de Sable)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "depredadores",
    cost: 6,
    attack: 7,
    defense: 5,
    image: "CK_Export/Tigre.png",
    rarity: "Épica",
    quote: "¡Colmillos que atraviesan el diamante!",
    description: "Felino prehistórico legendario. Sus colmillos perforan las defensas más gruesas sin piedad."
  },
  {
    id: "CK-17",
    name: "Turbo Cobra (Víbora)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "milenarios",
    cost: 2,
    attack: 3,
    defense: 1,
    image: "CK_Export/Turbo Cobra.png",
    rarity: "Común",
    quote: "¡Un roce y estarás acabado!",
    description: "Serpiente ancestral ultrarrápida. Cruza la barrera del sonido con un silbido fulminante."
  },
  {
    id: "CK-18",
    name: "Turbo Dragón (Wyvern)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "depredadores",
    cost: 8,
    attack: 8,
    defense: 6,
    image: "CK_Export/Turbo Dragon.png",
    rarity: "Legendaria",
    quote: "¡FUEGO SUPREMO DESDE LOS CIELOS!",
    description: "El dragón colosal que gobierna las cordilleras volcánicas. Su aliento derriba arenas completas."
  },
  {
    id: "CK-19",
    name: "Turbo Flash (Relámpago)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "miticos",
    cost: 4,
    attack: 5,
    defense: 2,
    image: "CK_Export/Turbo Flash.png",
    rarity: "Rara",
    quote: "¡Cae el trueno antes de la tormenta!",
    description: "Manifestación viviente de un rayo cósmico. Se desplaza instantáneamente detrás de las líneas rivales."
  },
  {
    id: "CK-20",
    name: "Turbo King (Monarca Bestial)",
    category: "kombat",
    categoryName: "Bestias Kombat",
    clan: "fugitivos",
    cost: 7,
    attack: 6,
    defense: 6,
    image: "CK_Export/Turbo King.png",
    rarity: "Épica",
    quote: "¡La velocidad forja mi corona!",
    description: "Líder bestial de las llanuras fugitivas. Inspira velocidad y audacia feroz a toda su manada."
  },

  // ==========================================
  // CATEGORÍA 3: TROMPOS FÍSICOS (20 CARTAS)
  // ==========================================
  {
    id: "TF-01",
    name: "Trompo Avispón",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "depredadores",
    cost: 2,
    cardType: "Hechizo / Velocidad",
    image: "Trompos_Export/Avispón.png",
    rarity: "Común",
    effect: "Permite que un personaje que acaba de entrar al campo ataque de inmediato en este turno.",
    realProductFlavor: "Punta de precisión aerodinámica. Corta el aire con un zumbido característico en combates rápidos."
  },
  {
    id: "TF-02",
    name: "Trompo Azteca",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "milenarios",
    cost: 4,
    cardType: "Defensa Local",
    image: "Trompos_Export/Azteca.png",
    rarity: "Épica",
    effect: "Crea un Escudo Giratorio en la arena que absorbe hasta 4 puntos de daño.",
    realProductFlavor: "Edición clásica coleccionista. Cuerpo con grabados de grecas folclóricas de alta estabilidad."
  },
  {
    id: "TF-03",
    name: "Trompo Cometín",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "milenarios",
    cost: 1,
    cardType: "Objeto / Ligero",
    image: "Trompos_Export/Cometín.png",
    rarity: "Común",
    effect: "Un aliado obtiene +1 de Fuerza inmediata en este turno gracias al impulso giratorio.",
    realProductFlavor: "Plástico ultraligero y vibrante. Diseñado especialmente para principiantes y trucos ágiles."
  },
  {
    id: "TF-04",
    name: "Trompo Diamante",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "fugitivos",
    cost: 4,
    cardType: "Objeto / Fortificación",
    image: "Trompos_Export/Diamante.png",
    rarity: "Rara",
    effect: "Otorga a todos tus personajes Fugitivos +2 de Vida máxima de forma permanente.",
    realProductFlavor: "Cuerpo de polímero cristalino translúcido de impacto extremo. Prácticamente irrompible."
  },
  {
    id: "TF-05",
    name: "Trompo Diamantín",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "milenarios",
    cost: 2,
    cardType: "Objeto / Curación",
    image: "Trompos_Export/Diamantín.png",
    rarity: "Común",
    effect: "Elimina todo el daño acumulado en una carta aliada en el campo de batalla.",
    realProductFlavor: "Diseño compacto en tonos esmeralda y cristal. Un deleite visual al girar bajo luz directa."
  },
  {
    id: "TF-06",
    name: "Trompo Draky",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "fugitivos",
    cost: 3,
    cardType: "Hechizo / Astucia",
    image: "Trompos_Export/Draky.png",
    rarity: "Común",
    effect: "Obliga al oponente a revelar su mano y descartar la carta de menor costo.",
    realProductFlavor: "Forma anatómica traviesa que genera trayectorias impredecibles de rebote en la arena."
  },
  {
    id: "TF-07",
    name: "Trompo Espectro",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "miticos",
    cost: 3,
    cardType: "Objeto / Equipamiento",
    image: "Trompos_Export/Espectro.png",
    rarity: "Rara",
    effect: "Otorga Invisibilidad a un campeón aliado: no puede ser atacado durante 1 turno.",
    realProductFlavor: "Punta de metal oscurecida. Balance giroscópico perfecto para giros prolongados y sigilosos."
  },
  {
    id: "TF-08",
    name: "Trompo Fénix",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "miticos",
    cost: 6,
    cardType: "Hechizo / Resurrección",
    image: "Trompos_Export/Fénix.png",
    rarity: "Legendaria",
    effect: "Elige un personaje aliado derrotado de tu cementerio y devuélvelo a tu mano.",
    realProductFlavor: "Gradiente de fuego cálido con corona reforzada. El símbolo de los campeones que nunca se rinden."
  },
  {
    id: "TF-09",
    name: "Trompo Jumbo Cobra",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "fugitivos",
    cost: 6,
    cardType: "Objeto / Pesado",
    image: "Trompos_Export/Jumbo Cobra.png",
    rarity: "Épica",
    effect: "Equipa a un aliado (+4 de Ataque). Si es derrotado, el trompo regresa a tu mano.",
    realProductFlavor: "Dimensiones sobredimensionadas XL. Mayor masa inercial para expulsar rivales fuera del círculo."
  },
  {
    id: "TF-10",
    name: "Trompo King Cobra",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "depredadores",
    cost: 5,
    cardType: "Ataque Mágico",
    image: "Trompos_Export/King Cobra.png",
    rarity: "Legendaria",
    effect: "Desata un giro explosivo que inflige 5 de daño a una carta enemiga al azar.",
    realProductFlavor: "El rey indiscutible de las competencias de impacto. Borde superior dentado y corona pesada."
  },
  {
    id: "TF-11",
    name: "Trompo Orión",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "miticos",
    cost: 2,
    cardType: "Objeto / Mejora",
    image: "Trompos_Export/Orión.png",
    rarity: "Rara",
    effect: "Permite al jugador robar 2 cartas adicionales de su mazo de Invocación.",
    realProductFlavor: "Punta giratoria con rodamiento libre. Máximo tiempo de giro continuo para jugadores analíticos."
  },
  {
    id: "TF-12",
    name: "Trompo Panther",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "depredadores",
    cost: 4,
    cardType: "Objeto / Emboscada",
    image: "Trompos_Export/Panther.png",
    rarity: "Rara",
    effect: "Se puede jugar como interrupción en el turno del rival para bloquear su ataque directamente.",
    realProductFlavor: "Acabado negro mate táctico. Menor resistencia al aire para impactos imprevistos."
  },
  {
    id: "TF-13",
    name: "Trompo Rex",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "miticos",
    cost: 5,
    cardType: "Hechizo Sísmico",
    image: "Trompos_Export/Rex.png",
    rarity: "Legendaria",
    effect: "Provoca un terremoto en la arena; todos los personajes enemigos pierden 2 de Vida.",
    realProductFlavor: "Cuerpo rugoso en verde jurásico. Su peso colosal impone dominio absoluto en el cuadrilátero."
  },
  {
    id: "TF-14",
    name: "Trompo Silver",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "milenarios",
    cost: 3,
    cardType: "Objeto / Escudo",
    image: "Trompos_Export/Silver.png",
    rarity: "Común",
    effect: "Refleja el próximo daño mágico que reciba tu héroe de vuelta hacia el oponente.",
    realProductFlavor: "Pintura metalizada especial de reflejo espejado. Destaca con brillo plateado bajo el sol."
  },
  {
    id: "TF-15",
    name: "Trompo Spider",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "fugitivos",
    cost: 3,
    cardType: "Objeto / Trampa",
    image: "Trompos_Export/Spider.png",
    rarity: "Común",
    effect: "Se juega boca abajo. El primer enemigo que ataque queda Enredado (no ataca este turno).",
    realProductFlavor: "Grabados de telaraña en relieve que facilitan un agarre firme y lanzamientos con efecto."
  },
  {
    id: "TF-16",
    name: "Trompo Tigre",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "depredadores",
    cost: 5,
    cardType: "Objeto / Equipamiento",
    image: "Trompos_Export/Tigre.png",
    rarity: "Rara",
    effect: "Equipa a un aliado para otorgarle Golpe Penetrante (el daño ignora escudos rivales).",
    realProductFlavor: "Patrones atigrados en naranja y negro con punta de choque agresiva para desgaste del oponente."
  },
  {
    id: "TF-17",
    name: "Trompo Turbo Cobra",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "milenarios",
    cost: 1,
    cardType: "Objeto / Descarte",
    image: "Trompos_Export/Turbo Cobra_.png",
    rarity: "Común",
    effect: "Roba 1 carta y descarta 1 carta para acelerar el ciclo de tu mazo.",
    realProductFlavor: "Perfil aerodinámico diseñado para minimizar la fricción y conseguir lanzamientos ultrarrápidos."
  },
  {
    id: "TF-18",
    name: "Trompo Turbo Dragón",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "depredadores",
    cost: 7,
    cardType: "Hechizo / Cataclismo",
    image: "Trompos_Export/Turbo Dragón.png",
    rarity: "Legendaria",
    effect: "Destruye todas las cartas de Arena/Locación activas e inflige 3 de daño al líder rival.",
    realProductFlavor: "Edición especial con aletas en espiral que cortan el aire emitiendo un silbido de dragón."
  },
  {
    id: "TF-19",
    name: "Trompo Turbo Flash",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "miticos",
    cost: 3,
    cardType: "Hechizo / Reubicación",
    image: "Trompos_Export/Turbo Flash.png",
    rarity: "Rara",
    effect: "Devuelve un personaje enemigo con costo 3 o menor a la mano de su dueño.",
    realProductFlavor: "Pintura fosforescente que brilla en la oscuridad. El trompo más veloz de la línea mítica."
  },
  {
    id: "TF-20",
    name: "Trompo Turbo King",
    category: "trompos",
    categoryName: "Trompos Físicos",
    clan: "fugitivos",
    cost: 6,
    cardType: "Ataque Mágico",
    image: "Trompos_Export/Turbo King.png",
    rarity: "Épica",
    effect: "Inflige daño igual a la suma del costo de todos tus personajes Fugitivos activos.",
    realProductFlavor: "Bisel dorado superior. Máxima corona de estabilidad en duelos de supervivencia continua."
  },

  // ==========================================
  // CATEGORÍA 4: ARENAS / LOCACIONES (20 CARTAS)
  // ==========================================
  {
    id: "AR-01",
    name: "Arenas Movedizas",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "fugitivos",
    cost: 2,
    image: "Arena_Export/Arenas Movedizas.png",
    rarity: "Común",
    effect: "Al final del turno, devuelve un campeón enemigo al azar a la mano de su dueño.",
    lore: "El desierto impenetrable que resguarda las guaridas clandestinas de los clanes fugitivos."
  },
  {
    id: "AR-02",
    name: "Bóveda del Cometa",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "fugitivos",
    cost: 6,
    image: "Arena_Export/Bóveda del Cometa.png",
    rarity: "Épica",
    effect: "Ningún jugador puede alterar ni reducir sus Puntos de Vida Base mientras esta arena esté activa.",
    lore: "Fortaleza de máxima seguridad subterránea donde se custodia el polvo mágico del gran impacto."
  },
  {
    id: "AR-03",
    name: "Campamento Panther",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "depredadores",
    cost: 3,
    image: "Arena_Export/Campamento Panther.png",
    rarity: "Común",
    effect: "Las cartas de emboscada o interrupción no tienen costo de energía la primera vez que se juegan.",
    lore: "Asentamiento nómada camuflado en la espesura del bosque de los Depredadores."
  },
  {
    id: "AR-04",
    name: "Caídas de Kamino",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "fugitivos",
    cost: 3,
    image: "Arena_Export/Caídas de Kamino.png",
    rarity: "Rara",
    effect: "Una vez por turno, puedes descartar una carta propia para robar inmediatamente otra del mazo.",
    lore: "Cataratas místicas que funcionan como portales interdimensionales de escape."
  },
  {
    id: "AR-05",
    name: "Cementerio de Juguetes",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "milenarios",
    cost: 5,
    image: "Arena_Export/Cementerio de Juguetes.png",
    rarity: "Rara",
    effect: "Invoca un Espíritu Cometa (1/1) cada vez que un aliado es destruido en combate.",
    lore: "Un valle sagrado cubierto de trompos antiguos y oxidados, venerados por los Milenarios."
  },
  {
    id: "AR-06",
    name: "Cimientos de Cristal",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "miticos",
    cost: 5,
    image: "Arena_Export/Cimientos de Cristal.png",
    rarity: "Épica",
    effect: "El primer personaje aliado que juegues en cada turno cuesta 1 menos de Energía.",
    lore: "Caverna subterránea donde brotan los cristales luminosos que alimentan la magia cósmica."
  },
  {
    id: "AR-07",
    name: "Ciudadela Plateada",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "milenarios",
    cost: 4,
    image: "Arena_Export/Ciudadela Plateada.png",
    rarity: "Rara",
    effect: "Todo el daño mágico dirigido a las cartas de esta ciudadela se reduce en 2 puntos.",
    lore: "Fortaleza majestuosa forjada completamente con aleaciones de plata y bronce antiguo."
  },
  {
    id: "AR-08",
    name: "La Arena Campeones",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "neutral",
    cost: 7,
    image: "Arena_Export/La Arena Campeones.png",
    rarity: "Legendaria",
    effect: "Todos los personajes en mesa restauran su Vida por completo al entrar a esta arena.",
    lore: "El gran coliseo dorado donde los cuatro clanes miden sus fuerzas en duelos legendarios."
  },
  {
    id: "AR-09",
    name: "La Pista de Carreras",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "milenarios",
    cost: 2,
    image: "Arena_Export/La Pista de Carreras.png",
    rarity: "Común",
    effect: "Todos los campeones con el nombre 'Turbo' ganan +2 de Ataque inmediato.",
    lore: "Desfiladero de piedra ancestral acondicionado para torneos de velocidad desenfrenada."
  },
  {
    id: "AR-09b",
    name: "Laboratorio del Rey",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "fugitivos",
    cost: 4,
    image: "Arena_Export/Laboratorio del Rey.png",
    rarity: "Rara",
    effect: "Permite buscar una carta de tipo 'Trompo Físico' en tu mazo y añadirla directamente a tu mano.",
    lore: "Guarida secreta donde científicos rebeldes ensamblan trompos con energía de pulso cometa."
  },
  {
    id: "AR-10",
    name: "Llanuras del Tirano",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "miticos",
    cost: 6,
    image: "Arena_Export/Llanuras del Tirano.png",
    rarity: "Épica",
    effect: "Incrementa el Ataque de todos los personajes presentes en el campo en +2.",
    lore: "Páramo árido donde alguna vez dominó Rex. El entorno impulsa la violencia desmedida."
  },
  {
    id: "AR-11",
    name: "Nido del Wyvern",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "depredadores",
    cost: 5,
    image: "Arena_Export/Nido del Wyvern.png",
    rarity: "Rara",
    effect: "Los ataques de los personajes del clan Depredadores no pueden recibir contragolpe.",
    lore: "Picos volcánicos elevados donde anidan las criaturas aéreas más feroces del clan."
  },
  {
    id: "AR-12",
    name: "Pozo de los Depredadores",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "depredadores",
    cost: 3,
    image: "Arena_Export/Pozo de los Depredadores.png",
    rarity: "Común",
    effect: "El jugador con menor puntuación de vida puede sacrificar un personaje para ganar +3 de Energía.",
    lore: "Cosa clandestina subterránea donde solo sobreviven los combatientes más implacables."
  },
  {
    id: "AR-13",
    name: "Red de la Viuda",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "fugitivos",
    cost: 4,
    image: "Arena_Export/Red de la Viuda.png",
    rarity: "Rara",
    effect: "Los personajes enemigos entran al combate agotados y no pueden atacar en su primer turno.",
    lore: "Un bosque tenebroso y tupido cubierto de resistentes hebras de telaraña mágica."
  },
  {
    id: "AR-14",
    name: "Ruinas de Draconia",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "depredadores",
    cost: 3,
    image: "Arena_Export/Ruinas de Draconia.png",
    rarity: "Rara",
    effect: "El líder oponente pierde 1 punto de vida al comienzo de su turno si no posee un escudo activo.",
    lore: "Restos de una fortaleza con esculturas draconianas de piedra que aún escupen ascuas moradas."
  },
  {
    id: "AR-15",
    name: "Santuario del Sol",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "miticos",
    cost: 3,
    image: "Arena_Export/Santuario del Sol.png",
    rarity: "Común",
    effect: "Genera +1 de Energía adicional en cada turno para el jugador que controle el santuario.",
    lore: "Altar piramidal bañado constantemente por un haz de luz solar mística concentrada."
  },
  {
    id: "AR-16",
    name: "Templo Milenario",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "milenarios",
    cost: 4,
    image: "Arena_Export/Templo Milenario.png",
    rarity: "Épica",
    effect: "Al final de tu turno, sana 1 de Vida a todos los campeones Milenarios que sigan en pie.",
    lore: "Antiguo altar de piedra rodeado de robles centenarios, corazón espiritual de los Milenarios."
  },
  {
    id: "AR-17",
    name: "Torreón de Espectro",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "miticos",
    cost: 4,
    image: "Arena_Export/Torreón de Espectro.png",
    rarity: "Rara",
    effect: "Tu mano de cartas permanece totalmente oculta e inmune a los efectos de descarte del rival.",
    lore: "Biblioteca flotante infinita que se desliza entre dimensiones paralelas."
  },
  {
    id: "AR-18",
    name: "Valle de Pruebas",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "milenarios",
    cost: 2,
    image: "Arena_Export/Valle de Pruebas.png",
    rarity: "Común",
    effect: "Todos los personajes de Costo 3 o menor obtienen +1 de Vida máxima adicional.",
    lore: "Círculo de combate abierto donde los aprendices demuestran su valía antes de recibir su trompo."
  },
  {
    id: "AR-19",
    name: "Volcán Sangriento",
    category: "arenas",
    categoryName: "Arenas / Locaciones",
    clan: "depredadores",
    cost: 6,
    image: "Arena_Export/Volcán Sangriento.png",
    rarity: "Épica",
    effect: "Inflige daño masivo a un objetivo equivalente a la fuerza total de tus personajes en juego.",
    lore: "Cráter en erupción constante, fuente del poder ardiente de los clanes más letales."
  }
];

const REVERSOS_INFO = [
  { id: "oro", name: "Dorado de Campeón", file: "Reverso_Export/reverso_Oro.png", badge: "Edición Oro" },
  { id: "color", name: "Color Oficial", file: "Reverso_Export/reverso_Color.png", badge: "Estándar" },
  { id: "bi", name: "Bicolor Clásico", file: "Reverso_Export/reverso_Bi.png", badge: "Bicolor" }
];
